apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: website
  name: backend-ghost-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: website
  name: backend
  labels:
    app: backend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
        - name: ghost-data
          persistentVolumeClaim:
            claimName: backend-ghost-data
      containers:
        - name: ghost
          image: ghost:latest
          env:
            - name: url
              value: "https://oechsler.it"
          volumeMounts:
            - mountPath: "/var/lib/ghost/content"
              name: ghost-data
          ports:
            - name: http
              containerPort: 2368
          
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: website

spec:
  ports:
    - protocol: TCP
      name: http
      port: 2368
  selector:
    app: backend

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: backend-admin-web
  namespace: website
  
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`oechsler.it`) && PathPrefix(`/ghost`)
    kind: Rule
    services:
    - name: backend
      port: 2368

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: backnd-admin-websecure
  namespace: website
  
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`oechsler.it`) && PathPrefix(`/ghost`)
    kind: Rule
    services:
    - name: backend
      port: 2368
  tls:
    certResolver: default