language: minimal
dist: bionic
services:
    - docker

branches:
    only:
        - master
        - dev
        - travis-ci

jobs:
    include:
        - stage: build
          name: "Build Docker Image"
          script:
              - echo "$REPO_PASSWORD" | docker login -u "$REPO_USERNAME" --password-stdin "$REPO_URL"
              - docker build . -t "$REPO_URL/$REPO_USERNAME/website:latest"
              - docker push "$REPO_URL/$REPO_USERNAME/website:latest"
        - stage: deploy
          name: "Deploy to Docker Registry"
          deploy:
              # Deploy to staging during development
              - provider: script
                script: echo "Staging goes here"
                on:
                    branch: dev
              # Deploy to production on release
              - provider: script
                script: echo "Production goes here"
                on:
                    branch: master
