dist: bionic
services:
    - docker
    
branches:
    only:
        - master
        - dev
        - travis-ci

script:
    - echo "$REPO_PASSWORD" | docker login -u "$REPO_USERNAME" --password-stdin registry.oechsler.it
    - docker build . -t registry.oechsler.it/samuel/website:latest
    - docker push registry.oechsler.it/samuel/website:latest
    