# Publish to Azure pipeline
# for the Oechsler Azure Web Service
# Copyright © 2019 - Samuel Oechsler

# Automatic ci triggers
trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - docs/*

# Automatic pull request triggers
pr:
  branches:
    include:
      - master
  paths:
    exclude:
      - docs/*

# Build image
pool:
  vmImage: ubuntu-16.04

# NodeJS build environment
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '11.x'
- script: 'yarn install'
- script: 'yarn build'
# Artifact publish task
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/build'