# Build on Azure pipeline for Docker
# Copyright © 2019 - Samuel Oechsler

# Automatic ci triggers
trigger:
    branches:
        include:
            - master
    paths:
        exclude:
            - docs/*

# Automatic pull request triggers
pr:
    paths:
        exclude:
            - docs/*

# Build image
pool:
    vmImage: ubuntu-16.04

steps:
    # Login to the Docker registry
    - script: |
          docker login -u "$(registryUser)" -p "$(registryPassword)" registry.oechsler.it
      env:
          registryUser: $(registryUser)
          registryPassword: $(registryPassword)
      displayName: 'Login to the Docker Registry'

    # Build the Docker image
    - script: |
          docker build -t registry.oechsler.it/$(registryUser)/$(imageName):staging .
      env:
          registryUser: $(registryUser)
          imageName: $(imageName)
      displayName: 'Build React App in Docker'

    # Push the built image to the Docker Registry
    - script: |
          docker push registry.oechsler.it/$(registryUser)/$(imageName):staging
      env:
          registryUser: $(registryUser)
          imageName: $(imageName)
      displayName: 'Push the built image to the Docker Registry'
