name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Create a Release
        uses: actions/create-release@v1.1.4
        with:
          tag_name: ${{ github.GITHUB_REF }}
          release_name: "Automatic Release"
          draft: true
      
      - name: Build & Publish Docker Image
        uses: elgohr/Publish-Docker-Github-Action@3.02
        with:
          name: oechsler/website
          username: ${{ secrets.DO_PERSONAL_TOKEN }}
          password: ${{ secrets.DO_PERSONAL_TOKEN }}
          registry: registry.digitalocean.com
          tags: "latest,${{ env.STATE_RELEASE_VERSION }}"
          no_push: ${{ github.event_name == 'pull_request' }}
          
      - name: Authenticate with Kubernetes
        uses: matootie/dokube@v1.3.4
        with:
          personalAccessToken: ${{ secrets.DO_PERSONAL_TOKEN }}
          clusterName: oechsler-kubernetes
          namespace: website
          
      - name: Deploy to Kubernetes
        run: kubectl set image deployment frontend \
             website=registry.digitalocean.com/oechsler/website:${{ env.STATE_RELEASE_VERSION }} \
             --record
