name: Build Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
  workflow_dispatch:
  
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - id: version_bump
        name: Bump version and push tag
        if: github.ref == 'refs/heads/master'
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          
      - name: Login to Azure via Azure-CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Retrieve Azure Container Registry credentials
        run: |
           az acr login -n oechsler

      - name: Build and publish Docker image
        uses: mr-smithers-excellent/docker-build-push@v5.2
        with:
          image: website
          tags: latest, ${{ steps.version_bump.outputs.new_tag }
          registry: oechsler.azurecr.io
          
      - name: Setup Azure Kubernetes Services
        uses: Azure/setup-kubectl@v1
      
      - name: Retrieve Azure Kubernetes Cluster credentials
        run: |
           az aks get-credentials -g Infrastructure -n oechsler
          
      - name: Deploy to Kubernetes
        if: github.ref == 'refs/heads/master'
        run: |
          kubectl config set-context --current --namespace=website
          kbectl set image deployment frontend website="oechsler.azurecr.io/website:${{ steps.version_bump.outputs.new_tag }}" --record
